apiVersion: v1
kind: ConfigMap
metadata:
  name: ocr-toolkit
  labels:
    {{- include "mefobase.labels" . | nindent 4 }}
{{- $config := .Values.ocrToolkitConfig }}
{{- if not $config }}
{{- $file := (.Files.Get "values/configs/ocr-toolkit-config.yaml" | fromYaml) }}
{{- $config = $file.ocrToolkitConfig }}
{{- end }}
data:
  ocr-toolkit: |-
{{ $config.configYaml | default "" | nindent 4 }}
