apiVersion: v1
kind: ConfigMap
metadata:
  name: mefobase-config
  labels:
    {{- include "mefobase.labels" . | nindent 4 }}
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.global.environment | quote }}
  TZ: "Asia/Ho_Chi_Minh"
  # Thêm các biến chung như KAFKA_BOOTSTRAP_SERVERS tại đây
  KAFKA_SERVERS: "kafka-cluster:9092"